package cn.makangning.mapper;

import cn.makangning.entity.Achievements;
import java.util.List;

public interface AchievementsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table achievements
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	int deleteByPrimaryKey(Integer aid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table achievements
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	int insert(Achievements record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table achievements
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	Achievements selectByPrimaryKey(Integer aid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table achievements
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	List<Achievements> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table achievements
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	int updateByPrimaryKey(Achievements record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table achievements
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	List<Achievements> selectByPrimaryUid(Integer uid);
}