package cn.makangning.service;

import java.util.List;

import cn.makangning.entity.Achievements;
import cn.makangning.entity.Course;

public interface AchievementsService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated Wed May 22 15:02:05 CST 2019
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated Wed May 22 15:02:05 CST 2019
     */
    int insert(Achievements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated Wed May 22 15:02:05 CST 2019
     */
    Achievements selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated Wed May 22 15:02:05 CST 2019
     */
    List<Achievements> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated Wed May 22 15:02:05 CST 2019
     */
    int updateByPrimaryKey(Achievements record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievements
     *
     * @mbg.generated Wed May 22 15:02:05 CST 2019
     */
    List<Achievements> selectByPrimaryUid(Integer uid);
}
