package cn.makangning.service;

import java.util.List;

import cn.makangning.entity.Classroom;

public interface ClassroomService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    int insert(Classroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    Classroom selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    List<Classroom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    int updateByPrimaryKey(Classroom record);
}
