package cn.makangning.service;

import java.util.List;

import cn.makangning.entity.Cost;

public interface CostService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Mon May 20 11:22:23 CST 2019
     */
    int deleteByPrimaryKey(Integer coid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Mon May 20 11:22:23 CST 2019
     */
    int insert(Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Mon May 20 11:22:23 CST 2019
     */
    Cost selectByPrimaryKey(Integer coid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Mon May 20 11:22:23 CST 2019
     */
    List<Cost> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost
     *
     * @mbg.generated Mon May 20 11:22:23 CST 2019
     */
    int updateByPrimaryKey(Cost record);
}
