package cn.makangning.service;

import java.util.List;

import cn.makangning.entity.Files;

public interface FileService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    int deleteByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    int insert(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    Files selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    List<Files> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    int updateByPrimaryKey(Files record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    List<Files> selectByPrimaryUid(Integer uid);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    List<Files> selectByPrimaryCid(Integer cid);
}
