package cn.makangning.service;

import java.util.List;

import cn.makangning.entity.Schedule;

public interface ScheduleService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Tue May 21 10:51:22 CST 2019
     */
    int deleteByPrimaryKey(Integer scid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Tue May 21 10:51:22 CST 2019
     */
    int insert(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Tue May 21 10:51:22 CST 2019
     */
    Schedule selectByPrimaryKey(Integer scid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Tue May 21 10:51:22 CST 2019
     */
    List<Schedule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Tue May 21 10:51:22 CST 2019
     */
    int updateByPrimaryKey(Schedule record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Tue May 21 10:51:22 CST 2019
     */
    List<Schedule> selectByPrimaryRid(int rid);
    
    /**
     * 冲突查询.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    List<Schedule> selectByWeekAndCoursetime(Schedule schedule);
}
