package cn.makangning.entity;

public class Achievements {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column achievements.aid
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	private Integer aid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column achievements.cid
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	private Course course;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column achievements.sresult
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	private Double sresult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column achievements.eresult
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	private Double eresult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column achievements.remarks
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column achievements.uid
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	private User user;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column achievements.aid
	 * @return  the value of achievements.aid
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public Integer getAid() {
		return aid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column achievements.aid
	 * @param aid  the value for achievements.aid
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public void setAid(Integer aid) {
		this.aid = aid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column achievements.cid
	 * @return  the value of achievements.cid
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public Course getCourse() {
		return course;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column achievements.cid
	 * @param course  the value for achievements.cid
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public void setCourse(Course course) {
		this.course = course;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column achievements.sresult
	 * @return  the value of achievements.sresult
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public Double getSresult() {
		return sresult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column achievements.sresult
	 * @param sresult  the value for achievements.sresult
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public void setSresult(Double sresult) {
		this.sresult = sresult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column achievements.eresult
	 * @return  the value of achievements.eresult
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public Double getEresult() {
		return eresult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column achievements.eresult
	 * @param eresult  the value for achievements.eresult
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public void setEresult(Double eresult) {
		this.eresult = eresult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column achievements.remarks
	 * @return  the value of achievements.remarks
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column achievements.remarks
	 * @param remarks  the value for achievements.remarks
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column achievements.uid
	 * @return  the value of achievements.uid
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public User getUser() {
		return user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column achievements.uid
	 * @param user  the value for achievements.uid
	 * @mbg.generated  Wed May 22 16:40:37 CST 2019
	 */
	public void setUser(User user) {
		this.user = user;
	}

	@Override
	public String toString() {
		return "Achievements [aid=" + aid + ", course=" + course + ", sresult=" + sresult + ", eresult=" + eresult
				+ ", remarks=" + remarks + ", user=" + user + "]";
	}
}