package cn.makangning.entity;

public class Classroom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.rid
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.rname
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    private String rname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.number
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom.state
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.rid
     *
     * @return the value of classroom.rid
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.rid
     *
     * @param rid the value for classroom.rid
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.rname
     *
     * @return the value of classroom.rname
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.rname
     *
     * @param rname the value for classroom.rname
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    public void setRname(String rname) {
        this.rname = rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.number
     *
     * @return the value of classroom.number
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.number
     *
     * @param number the value for classroom.number
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom.state
     *
     * @return the value of classroom.state
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom.state
     *
     * @param state the value for classroom.state
     *
     * @mbg.generated Mon May 20 09:41:41 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

	@Override
	public String toString() {
		return "Classroom [rid=" + rid + ", rname=" + rname + ", number=" + number + ", state=" + state + "]";
	}
    
    
}