package cn.makangning.entity;

import java.math.BigDecimal;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cid
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cname
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.chours
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    private Integer chours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cmoney
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    private BigDecimal cmoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cid
     *
     * @return the value of course.cid
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cid
     *
     * @param cid the value for course.cid
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cname
     *
     * @return the value of course.cname
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cname
     *
     * @param cname the value for course.cname
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.chours
     *
     * @return the value of course.chours
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    public Integer getChours() {
        return chours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.chours
     *
     * @param chours the value for course.chours
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    public void setChours(Integer chours) {
        this.chours = chours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cmoney
     *
     * @return the value of course.cmoney
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    public BigDecimal getCmoney() {
        return cmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cmoney
     *
     * @param cmoney the value for course.cmoney
     *
     * @mbg.generated Tue May 21 21:24:27 CST 2019
     */
    public void setCmoney(BigDecimal cmoney) {
        this.cmoney = cmoney;
    }

	@Override
	public String toString() {
		return "Course [cid=" + cid + ", cname=" + cname + ", chours=" + chours + ", cmoney=" + cmoney + "]";
	}
}