package cn.makangning.entity;

public class Files {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.fid
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.uid
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    private User user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.cid
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    private Course course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.url
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.fid
     *
     * @return the value of file.fid
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.fid
     *
     * @param fid the value for file.fid
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.uid
     *
     * @return the value of file.uid
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    public User getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.uid
     *
     * @param user the value for file.uid
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.cid
     *
     * @return the value of file.cid
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    public Course getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.cid
     *
     * @param course the value for file.cid
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    public void setCourse(Course course) {
        this.course = course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.url
     *
     * @return the value of file.url
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.url
     *
     * @param url the value for file.url
     *
     * @mbg.generated Wed May 22 16:40:48 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

	@Override
	public String toString() {
		return "File [fid=" + fid + ", user=" + user + ", course=" + course + ", url=" + url + "]";
	}
}