package cn.makangning.entity;

public class Schedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.scid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    private Integer scid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.cid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    private Course course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.week
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    private Integer week;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.coursetime
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    private Integer coursetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.rid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    private Classroom classroom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.uid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    private User user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.scid
     *
     * @return the value of schedule.scid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public Integer getScid() {
        return scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.scid
     *
     * @param scid the value for schedule.scid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public void setScid(Integer scid) {
        this.scid = scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.cid
     *
     * @return the value of schedule.cid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public Course getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.cid
     *
     * @param course the value for schedule.cid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public void setCourse(Course course) {
        this.course = course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.week
     *
     * @return the value of schedule.week
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.week
     *
     * @param week the value for schedule.week
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public void setWeek(Integer week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.coursetime
     *
     * @return the value of schedule.coursetime
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public Integer getCoursetime() {
        return coursetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.coursetime
     *
     * @param coursetime the value for schedule.coursetime
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public void setCoursetime(Integer coursetime) {
        this.coursetime = coursetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.rid
     *
     * @return the value of schedule.rid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public Classroom getClassroom() {
        return classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.rid
     *
     * @param classroom the value for schedule.rid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public void setClassroom(Classroom classroom) {
        this.classroom = classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.uid
     *
     * @return the value of schedule.uid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public User getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.uid
     *
     * @param user the value for schedule.uid
     *
     * @mbg.generated Tue May 21 19:33:37 CST 2019
     */
    public void setUser(User user) {
        this.user = user;
    }

	@Override
	public String toString() {
		return "Schedule [scid=" + scid + ", course=" + course + ", week=" + week + ", coursetime=" + coursetime
				+ ", classroom=" + classroom + ", user=" + user + "]";
	}
}