package cn.makangning.entity;

public class User {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.uid
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.Email
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.sex
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	private Long phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.address
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.img
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.school
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	private String school;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.type
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.state
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.uid
	 * @return  the value of user.uid
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.uid
	 * @param uid  the value for user.uid
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.Email
	 * @return  the value of user.Email
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.Email
	 * @param email  the value for user.Email
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sex
	 * @return  the value of user.sex
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sex
	 * @param sex  the value for user.sex
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public Long getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public void setPhone(Long phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.address
	 * @return  the value of user.address
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.address
	 * @param address  the value for user.address
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.img
	 * @return  the value of user.img
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.img
	 * @param img  the value for user.img
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.school
	 * @return  the value of user.school
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.school
	 * @param school  the value for user.school
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public void setSchool(String school) {
		this.school = school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.type
	 * @return  the value of user.type
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.type
	 * @param type  the value for user.type
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.state
	 * @return  the value of user.state
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.state
	 * @param state  the value for user.state
	 * @mbg.generated  Fri Dec 21 22:25:05 CST 2018
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	@Override
	public String toString() {
		return "User [uid=" + uid + ", email=" + email + ", name=" + name + ", password=" + password + ", sex=" + sex
				+ ", phone=" + phone + ", address=" + address + ", img=" + img + ", school=" + school + ", type=" + type
				+ ", state=" + state + "]";
	}
    
    
}